### PR TITLE
[scroll_overlay] Use different sized items 

### PR DESCRIPTION
**Pull request by passsy**
Increate cell size with each index by 1
  - [x] Flutter
  - [x] iOS 
  - [X] Android

It turned out that different sized cells cause a different scrolling behavior on iOS (https://github.com/flutter/flutter/issues/32448). This change allows testing this scenario.

- Recreate ancient android project which wasn't compiling
- Reduce Android divider height to 0 to better align with Flutter rendering

### CODE REVIEW

**Comment by passsy** [comment]
@LongCatIsLooong wanna merge this PR?

**Comment by xster** [comment]
Thanks for bringing this project up to date. Could you add a screenshot for before and after?

**Comment by passsy** [comment]
|Before   |After   |
|---|---|
|Screenshot_1598285174|Screenshot_1598284785|

The items now increase by 1 logical pixel with each item. Analog on iOS

**Comment by passsy** [comment]
### Note

The iOS scrolling is broken on `Flutter (Channel master, 1.22.0-2.0.pre.36, on Mac OS X 10.15.6 19G2021, locale en-GB)`. Fling doesn't work and scrolling is ~4x slower.

`git bisect` pointed to https://github.com/flutter/flutter/commit/be9bc8cb3942bda5d8ef4e44b44616c470625e18 where the bug was introduced

**Comment by xster** [comment]
uh oh, that's concerning. Do we have a bug for this issue?

**Comment by passsy** [comment]
False alarm, my bad. Everything works after `flutter clean`.

**Comment by InMatrix** [comment]
Just tried this PR today for a demo. It worked very well. Since there is already an approval from @LongCatIsLooong for the PR, I'm merging this. Thank you for your contribution, @passsy.

**Pull request merged**
