### PR TITLE
Add scroll-physics logging in scroll_overlay

### PR DESCRIPTION
**Pull request by gnprice**
This is the last part of the further enhancements after #13 that I've been using for my investigations the past couple of weeks. It consists of two related commits:

#### [scroll_overlay] Add a place to customize the scroll physics

This has been very convenient for experimenting with different
scroll physics in my recent investigations, providing a way to
do so without creating rebase conflicts with other changes to
this `ListView.builder` call.

This is especially useful in combination with the next commit,
adding a piece of debug logging.

#### [scroll_overlay] Add debug print on createBallisticSimulation

This has been extremely convenient in my recent scrolling
investigations.

Because the ScrollPhysics protocol is a bit subtle to hook into
correctly, and requires some boilerplate, inserting debug logging
for it is a bit more complicated than just writing down a
`debugPrint` call of one's choice.  So it benefits from having
this permanent infrastructure in the app.

---

The second commit leaves the debug logging it adds enabled by default. That's not what one would do in the framework or in a normal app; but I think it makes sense here, given that this is a test app and the logging is right at the core of what the app is made to test.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Sharing on all 3 for consistency: I was so very excited to see https://github.com/flutter/platform_tests/pull/13 that I forgot myself and made an error, actually 2. I should have sought a second reviewer on the PR as is our review guidelines. And I should have ensured tests were included, or that test exemption had been granted. 😅

Can you add a test for this PR? It ensures we do not end up removing your change accidentally. :)

**Comment by gnprice** [comment]
Test added! PTAL.

**Review by Piinks — APPROVED** [review]
Also LGTM! Thank you for all of these improvements. I think I managed the merge conflict this time. :)

**Comment by gnprice** [comment]
Thank you!

It looks like the merge on this one needs a fixup: #17.

(Which I guess reminds us of why it'd be great to have these new tests run automatically on PRs, and/or to have the autosubmit infra running on this repo.)

**Pull request merged**
