### PR TITLE
Update scroll_overlay further

### PR DESCRIPTION
**Pull request by gnprice**
This follows on the boring part of #13 with further boring updates that just keep the app smoothly building and running.

---

#### [scroll_overlay] Upgrade Android Gradle Plugin to 4.x; Gradle to 6.7.x

I've started seeing the symptoms of flutter/flutter#53657 when I
try to run this app.  That blocks building and running it.

I don't totally understand why that's happening, as that issue is
said to only appear on a range of AGP versions later than the 3.5.0
this is using.  Nor do I understand why it started happening for me
when it wasn't before.

But regardless of the cause, thankfully the symptoms are resolved by
following the recommendation in that issue thread:
  https://github.com/flutter/flutter/issues/53657#issuecomment-795808016
to upgrade AGP.  And upgrading seems for the best anyway.

We go for the latest 4.x version, as called for there.  I just let
Android Studio do the upgrade according to its recommendations, and
then bumped compileSdkVersion to the new requirement.

#### [scroll_overlay] Update pubspec.lock for current Flutter main

Given the purpose of this app, one wants to use it with main
more than with stable.  Make that more convenient by applying
the updates it wants to make to pubspec.lock, so that running it
doesn't make those updates and dirty the tree.

#### [scroll_overlay] Add another generated file to gitignore

This file is created when running the app with current Flutter main.

---

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
This LGTM, but would probably be better combined with one of the other PRs. I was so very excited to see #13 that I forgot myself and made an error, actually 2. I should have sought a second reviewer on the PR as is our review guidelines. And I should have ensured tests were included, or that test exemption had been granted. 😅 
Having to find a second reviewer for this and the others may slow this down a bit, but is fine if you prefer to keep these all separate, but for this change I am not sure how to test it easily.

**Comment by gnprice** [comment]
Added a pair of smoke-tests for the app.

The integration test has the side benefit of checking that the build works, which is what was breaking for me before the first commit in this PR. So perhaps for this repo that's a good enough version of a test for that fix.

**Review by Piinks — APPROVED** [review]
Thank you! LGTM!

**Comment by Piinks** [comment]
Confirmed bot non-compliance on discord for now, merging away. :)

**Pull request merged**
